baseurl = "https://golangkorea.github.io/"
languageCode = "en-us"
title = "Golang Korean Community"
builddrafts = false
canonifyurls = true
theme = "Hugo-Octopress"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]

customCSS = ["css/custom.css"]

# searchEngineURL = "https://www.google.com/search"
disqusShortname = "UA-82835198-1"
rss = true


sidebarHeader = "못 먹어도 Go인 세상"
sidebarText = "새로운 도전과 개발의 재미를 Go를 통해 만끽해 보세요"

github = "https://github.com/golangkorea/golangkorea-hugo/"
facebook = "https://www.facebook.com/groups/golangko/"
googleplus = "https://plus.google.com/communities/115721275599816202991"

sidebarRecentLimit = "5"

sidebarMenuEnabled = true
sidebarMenuHeader = "Join Us"
sidebarNewWindow  = true

highlightTheme = "darcula"

[[menu.sidebar]]
  Name = "GitHub Organization"
  URL = "https://github.com/golangkorea"
  weight = 0

[[menu.sidebar]]
  Name = "Gitter Room"
  URL = "https://gitter.im/golang-korean-community/golangkorea.github.io?utm_source=share-link&utm_medium=link&utm_campaign=share-link"
  weight = 1

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"